version: '3'
services:
  scrapy:
    build:
      context: .
      dockerfile: docker/Dockerfile
      
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3307
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
